### ISSUE TITLE
是否可以新增开关翻译的功能

### ISSUE THREAD

**Issue by ExplodingDragon** [waylyrics/waylyrics#134]
是否可以新增开关翻译的功能, 我看到歌词翻译似乎是强制开启的

![图片](https://github.com/waylyrics/waylyrics/assets/33776693/81de4282-d7ff-4200-bd09-79a9ab87dd46)

**Comment by poly000** [comment]
https://github.com/waylyrics/waylyrics/blob/b95400b86b2a447a0abadc3be208cd3911db19eb/src/sync/lyric/scroll.rs#L61-L87

晚上回家我加一个lyric-display-mode
默认为both，可以是tran/orig only
用GSettings中持久化

**Comment by poly000** [comment]
先写到Config了，日后再写一个配置界面
