### ISSUE TITLE
读取lrc文件中的翻译

### ISSUE THREAD

**Issue by sf467** [waylyrics/waylyrics#241]
**你的功能建议是否与问题有关？请描述。**
有些情况下，lrc文件中会将歌词翻译写为与原歌同一时间的歌词，如：

[00:23.22]ホワイトボードでひしめき合う
[00:23.22]在白板前争先恐后
[00:28.59]落書き 自由な願い事
[00:28.59]涂鸦自由的愿望
[00:33.88]放課後のチャイム 夕陽に響いても
[00:33.88]就算放学后的铃声响彻夕阳
[00:39.15]夢見るパワー ディスれないね 生憎
[00:39.15]也不能轻视梦想的力量  真遗憾

但，waylyrics现在只能显示单行的，或是原歌词，或是翻译，不能同时显示

**描述你希望的解决方案**

希望可以添加如下逻辑：
同一时间轴的两句歌词，将下面那一句视为翻译

**描述你考虑过的替代方案**
将同一时间轴的俩句歌词视为同一句，分前后显示

**附加上下文**
> 在这里添加有关功能建议的任何其他背景信息或截图

**Comment by mokurin000** [comment]
@sf467 之前考虑过，但最终还是希望用户写工具拆分并显示指定使用翻译lrc，因为有些字幕工具生成的lrc会在同样的时间戳有空行和非空行（同样是非标准LRC），可能是因为其空行断连逻辑实现不完善。
最近身上还有一些单子，闲下来后我试试写一下在自动加载本地LRC时可选启用。

**Comment by sf467** [comment]
> @sf467 之前考虑过，但最终还是希望用户写工具拆分并显示指定使用翻译lrc，因为有些字幕工具生成的lrc会在同样的时间戳有空行和非空行（同样是非标准LRC），可能是因为其空行断连逻辑实现不完善。 最近身上还有一些单子，闲下来后我试试写一下在自动加载本地LRC时可选启用。

十分感谢，另外请问目前本软件有自动导入翻译lrc的方法吗，是否需要特定的文件名格式

**Comment by mokurin000** [comment]
> > @sf467 之前考虑过，但最终还是希望用户写工具拆分并显示指定使用翻译lrc，因为有些字幕工具生成的lrc会在同样的时间戳有空行和非空行（同样是非标准LRC），可能是因为其空行断连逻辑实现不完善。 最近身上还有一些单子，闲下来后我试试写一下在自动加载本地LRC时可选启用。
> 
> 十分感谢，另外请问目前本软件有自动导入翻译lrc的方法吗，是否需要特定的文件名格式

#165 暂时没有，之前一直没想通怎么自动从环境语言代码匹配到对应的 ISO lang code，不过刚刚想了一下，可以用户输入一个数组，优先级从高到低；一样是LRC格式

**Comment by mokurin000** [comment]
> > @sf467 之前考虑过，但最终还是希望用户写工具拆分并显示指定使用翻译lrc，因为有些字幕工具生成的lrc会在同样的时间戳有空行和非空行（同样是非标准LRC），可能是因为其空行断连逻辑实现不完善。 最近身上还有一些单子，闲下来后我试试写一下在自动加载本地LRC时可选启用。
> 
> 十分感谢，另外请问目前本软件有自动导入翻译lrc的方法吗，是否需要特定的文件名格式

现在可以自动读取 .<系统语言BCP 49 code>.lrc了

**Comment by sf467** [comment]
可以改，但是歌曲数量是在太多了，实在没办法一首一首改出来
还是期待一下那个可选功能吧

**Comment by mokurin000** [comment]
> 可以改，但是歌曲数量是在太多了，实在没办法一首一首改出来 还是期待一下那个可选功能吧

ok 手上的急单今天一天干完了 应该很快会有空

**Comment by mokurin000** [comment]
已经可以了~ 另外现在的优先级是 独立的符合locale code后缀名的lrc文件优先级高于提取原LRC

**Comment by mokurin000** [comment]
因为这是workaround暂时不打算对手动导入LRC也启用，之后有空我会把这部分逻辑写成一个独立的提取工具

**Comment by sf467** [comment]
好快？！
太感谢了
