### ISSUE TITLE
[文档] 在README增加DeadBeef播放器

### ISSUE THREAD

**Issue by Ypixcm** [waylyrics/waylyrics#245]
![截图_2024-07-21_12-05-15](https://github.com/user-attachments/assets/dee8282e-de76-4719-a4e4-e0d6b0e1c8bb)
DeadBeef+waylyrics 工作良好
但需要 deadbeef-mpris2-plugin

**Comment by mokurin000** [comment]
正打算出门和老婆约会，等我回来？或者你可以PR（按readme中格式写进去就好）
