### ISSUE TITLE
[FEAT] 隐藏桌面Panel的图标，只显示托盘图标

### ISSUE THREAD

**Issue by ReidX7** [waylyrics/waylyrics#250]
Mint 22 Cinnamon 下会显示panel的图标（不知道是这个发行版会这样还是默认就这样），能不能隐藏掉呢？
另外图标能换个icon吗？跟默认的图标风格不一致

**Comment by mokurin000** [comment]
@ReidX7 > Mint 22 Cinnamon 下会显示panel的图标（不知道是这个发行版会这样还是默认就这样）

waylyrics不会试图通过支持协议实现隐藏任务栏等需求，因为Wayland以后各家协议割裂。此外，需要的特性有官方支持时，往往可以通过窗口规则针对启用。

> 另外图标能换个icon吗？跟默认的图标风格不一致

Waylyrics 不是 Linux Mint 的一部分，目前的图标是 zenvie 使用AI设计并转换矢量图、进行修正得到。如有此需要，可以自行编写patch、设计符合您使用的主题的图标，打包一份更换图标的分发。

**Comment by ReidX7** [comment]
明白了，感谢

**Comment by mokurin000** [comment]
@ReidX7 看起来 Cinnamon 还是一个只支持X的桌面环境，支持使用 EWMH 控制窗口。另外可以参考使用wmctrl。

**Comment by ReidX7** [comment]
`wmctrl -r Waylyrics -b toggle,skip_taskbar` 确实可以隐藏掉taskbar， 感谢
