### ISSUE TITLE
Improvements for multiple monitor setups

### ISSUE THREAD

**Issue by BruceZhang1993** [waylyrics/waylyrics#263]
Improvements for multiple monitor setups
对于多显示器配置的优化建议

**描述你希望的解决方案**

- 支持同时在一个或多个（或全部）显示器上以相同对齐方式显示
- 支持选择各显示器采用不同对齐方式/不同主题

**Comment by mokurin000** [comment]
@BruceZhang1993 啊 GApplication会单例化..
gtk会申请单一 app_id

**Comment by BruceZhang1993** [comment]
感觉应该开多个歌词窗口吧，而不是多个实例

**Comment by mokurin000** [comment]
@BruceZhang1993 emmm 多个窗口吗
按窗口设置倒是可以
