### ISSUE TITLE
歌词显示窗口过大

### ISSUE THREAD

**Issue by jheroy** [waylyrics/waylyrics#265]
我使用的是arch 系统 Hyprland窗口管理器，  歌词窗口最小如下图所示， 比歌词显示区域大了一圈。 在没有窗口装饰的情况下， 希望可以缩小到一行， 不要上下空白。
![image](https://github.com/user-attachments/assets/b8c1f442-1f00-408d-bd9c-2b594f9e40fd)

**Comment by taoky** [comment]
我记得 Wayland 下窗口的大小在创建之后就不能够随意修改……建议修改 Hyperland 配置匹配窗口然后去掉阴影？

**Comment by jheroy** [comment]
去掉模糊， 边框，阴影后，基本上不可见了， 但是右边还是有一条竖线：
![image](https://github.com/user-attachments/assets/ce304bd3-181a-4dbe-a07e-9b62abf5538b)

**Comment by jheroy** [comment]
目前发现右边那条竖线在左右拖动的过程中，有小概率（在某些特定位置）会消失。

**Comment by mokurin000** [comment]
@jheroy https://github.com/waylyrics/waylyrics/blob/3f5eeabe74dfc13a14c4f381d2cd122fff107d1a/src/app/mod.rs#L9
这个算是个历史问题，窗口最低高度被写死为120px了

**Comment by mokurin000** [comment]
> 去掉模糊， 边框，阴影后，基本上不可见了， 但是右边还是有一条竖线： ![image](https://private-user-images.githubusercontent.com/504766/381480165-ce304bd3-181a-4dbe-a07e-9b62abf5538b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE4MjU1MTUsIm5iZiI6MTczMTgyNTIxNSwicGF0aCI6Ii81MDQ3NjYvMzgxNDgwMTY1LWNlMzA0YmQzLTE4MWEtNGRiZS1hMDdlLTliNjJhYmY1NTM4Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExN1QwNjMzMzVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iYzdkNjNiOWE4OWI3NDk4ZDljNjdlMmRlYmViMTI5NmZmM2MwODQyNDFkMzQ4ZDU2MWM2MmZjN2Q1MjVhMjUyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.rVuelqgOZqwj6XIoGDGhtVqEt20B039Vht53-8bkYdk)

暂定为 Hyprland 相关bug
Plasma/GNOME下威能复现
