### ISSUE TITLE
docs: translation for contribution.md and `build guide ubuntu`

### ISSUE THREAD

**Issue by mokurin000** [waylyrics/waylyrics#271]
i18n for docs

- [ ] contribution
- [ ] Build Guide Ubuntu ZH

**Comment by Boyan-Wang-cn** [comment]
Hello, I noticed that this task has not been assigned yet. Can I take it on?

**Comment by mokurin000** [comment]
> Hello, I noticed that this task has not been assigned yet. Can I take it on?

You are welcome to submit a PR. add `fix #271` in its description
