### ISSUE TITLE
Add GUI Theme Configurator

### ISSUE THREAD

**Issue by Integral-Tech** [waylyrics/waylyrics#56]
- [ ] RGB color panel
- [ ] Font size & font type customization

**Comment by poly000** [comment]
also, for users want set different font for different languages, check https://stackoverflow.com/a/6487102/13121439

**Comment by poly000** [comment]
另：从歌曲封面图提取主要色彩作为背景色/字体色？

**Comment by Integral-Tech** [comment]
> 另：从歌曲封面图提取主要色彩作为背景色/字体色？

挺不错的主意

**Comment by poly000** [comment]
external CSS editor should be much better
