### ISSUE TITLE
[BUG] unexpected border on i3 (picom)

### ISSUE THREAD

**Issue by AllenWu233** [waylyrics/waylyrics#68]
如何隐藏窗口的背景、边框，达到示例图中的效果？

**Comment by poly000** [comment]
诶？背景现在默认theme就是透明的啊
边框默认热键现在是Ctrl-D

**Comment by AllenWu233** [comment]
> 

那应该是我的问题了，我回去配置一下i3和picom

**Comment by poly000** [comment]
@AllenWu233 可以给个截图嘛
至今在大都wm/de没问题，i3的话是X11 也不该有问题

**Comment by AllenWu233** [comment]
![Screenshot_20230808_215226](https://github.com/waylyrics/waylyrics/assets/107256524/25af6aff-7416-42aa-9b60-be693c02718d)

如上，背景已经调到透明，但是黑色边框没能去除

**Comment by poly000** [comment]
朋友说黑线是picom的期望行为，我还没有确定

**Comment by poly000** [comment]
根据 Superuser 的[回答](https://superuser.com/a/1716544)，i3默认会为窗口设置边框

i3用户可以设置快捷键或为边框风格配置快捷键[^0]
[^0]: https://i3wm.org/docs/4.3/userguide.html#_changing_border_style

**Comment by AllenWu233** [comment]
终于解决了。原来问题出在gtk4，与i3和picom关系不大
在Waylyrics的theme文件或`~/.config/gtk-4.0/gtk.css`中加上这行就可以了：
```
window {
    border: 0;
}
```

**Comment by poly000** [comment]
> 终于解决了。原来问题出在gtk4，与i3和picom关系不大 在Waylyrics的theme文件或`~/.config/gtk-4.0/gtk.css`中加上这行就可以了：
> 
> ```
> window {
>     border: 0;
> }
> ```

az，结果原来是主题设置..
